# POST http://127.0.0.1:8888/api/user/sendVerificationMail?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
# Content-Type: application/json
# Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y2ZGNlNDZkZmRjMmU5ZmJkMDBlZCIsImlhdCI6MTY0ODM0MzcyMSwiZXhwIjoxNjQ4NDMwMTIxfQ.BX3q7PAsjal-JFJ61synBFOaqTm16rfrJpMZLozxvhE

# {
#     "email":"ab3atef@yahoo.com"
# }
###
GET http://127.0.0.1:8888/api/user/getUserData?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

###
POST http://127.0.0.1:8888/api/user/forgetPassword?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "email":"ahmed0103060120@gmail.com"
}

###
POST http://127.0.0.1:8888/api/user/sendCode?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "email":"ahmed0103060120@gmail.com",
    "code":"6684219"
}
###
POST http://127.0.0.1:8888/api/user/resetPassword?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGEwYjg0YThmM2M5NDU1ODU4YTFhNyIsImlhdCI6MTY0OTEwOTQwMSwiZXhwIjoxNjQ5MTA5NDYxfQ.Fq5HoOwFFG2Idyb1dSDX86ABTqL8XjUWd3BskxfH7LU

{
    "newPassword":"x",
    "code":"6684219"
}
###
POST http://127.0.0.1:8888/api/user/register?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "userName":"ahmed",
    "email": "tERst@test.co",
    "phone": "98076258",
    "password": "sdsdwewc"
}

###
POST http://127.0.0.1:8888/api/user/FFactorAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "userName": "at33f",
    "password": "x"
}
###
POST http://127.0.0.1:8888/api/user/TwoFactorAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "userName": "at33f",
    "otp": "OpO2MzjhtuPoxNV0"
}
###
POST http://127.0.0.1:8888/api/user/logout?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTFlY2FlMDAwZWM0NmJhNWYwOGQzNCIsImlhdCI6MTY0OTgxMjg4MSwiZXhwIjoxNjQ5ODk5MjgxfQ.3yK8Ys7wzflqmbj42Sn6yMaL3rw7sENTWSHbv7oD9fM"
}

###
POST http://127.0.0.1:8888/api/user/getNewAccessToken?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "token":"--------------------------AyNDE2NX0.f9AowTkNEVNvicM0yx2B-QStcmAJIeA5bnlI97_lA_8"
}
###
GET http://127.0.0.1:8888/api/testAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y2ZGNlNDZkZmRjMmU5ZmJkMDBlZCIsImlhdCI6MTY0ODMyNjgwMiwiZXhwIjoxNjQ4NDEzMjAyfQ.4kvRFC24W5sTgfSWUxNN7yjjzcF14StVePtXfqZcL5A

###
PUT  http://127.0.0.1:8888/api/user/updatePassword?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y2ZGNlNDZkZmRjMmU5ZmJkMDBlZCIsImlhdCI6MTY0ODMyNjgwMiwiZXhwIjoxNjQ4NDEzMjAyfQ.4kvRFC24W5sTgfSWUxNN7yjjzcF14StVePtXfqZcL5A

{
    "password": "x",
    "newPassword": "xx"  
}

###
DELETE http://127.0.0.1:8888/api/user/deleteAccount?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzExZjVlOTM0MTczNjFlMjk1ZWRiZCIsImlhdCI6MTY0NzM4NjQ2NSwiZXhwIjoxNjQ3NDcyODY1fQ.iZVsV3YlvkISBlpPVQmzcr_v0HNTA7werLolRB6zkZQ

{
    "password": "x",
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzExZjVlOTM0MTczNjFlMjk1ZWRiZCIsImlhdCI6MTY0NzM4NjQ2NX0.yzBLy8LzawhpxNtFo_6JkVZ3ctBbAzBm_8Bcbrbiho0"
}

###==================================PLAN============================================
POST http://127.0.0.1:8888/api/plan/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDU5MDYyMCwiZXhwIjoxNjUwNjc3MDIwfQ.ih81ssDZ3iDHnyfR6IvDSXN6JZ-hIroiX97j1bfMl9I

{
    "planType":"lOnG",
    "planName":"GOLD LiteX",
    "cryptoName":"BtC",
    "algorithm":"SHA-256",
    "planDuration":2,
    "profitability":200,
    "price":9000
}
###
GET http://127.0.0.1:8888/api/plan?planType=loNg&cryptoName=BtC&key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDU5MTgwNCwiZXhwIjoxNjUwNjc4MjA0fQ.g4xeAfIClVIPkuxEuPqPJS4klNg-pK5C5ior0PpE6lU

###
GET http://127.0.0.1:8888/api/plan/admin?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI

###
GET http://127.0.0.1:8888/api/plan/620a3e3e50d15271dd99d31a?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1IjoibWVubjk5ODc4NzZhYWRobTlkeHgiLCJpYXQiOjE2NDU4ODQyMzQsImV4cCI6MTY0NTk3MDYzNH0.y0cYbV0oJKQz6wFyO89Bjx7UzuzaM47A8lTOVu4RwiQ

###
PUT http://127.0.0.1:8888/api/plan/update/62622322fabaa330a520d66e?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDU5MDYyMCwiZXhwIjoxNjUwNjc3MDIwfQ.ih81ssDZ3iDHnyfR6IvDSXN6JZ-hIroiX97j1bfMl9I

{
    "planType":"long",
    "planName":"regular",
    "cryptoName":"btc",
    "algorithm":"ethash",
    "planDuration":1,
    "profitability":150,
    "price":1000,
    "availability":"true"
}

###
DELETE  http://127.0.0.1:8888/api/plan/delete/62151626448be90dcf016713?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1IjoibWVubjk5YWFkaG05ZHh4IiwiaWF0IjoxNjQ1NTQ5MDc2LCJleHAiOjE2NDU2MzU0NzZ9.oD4kyDCoyINYJnYpU1vXytB43h_Eo_3qxlwC62cpYaE
###==================================PLAN-CONTRACT============================================
POST https://cominer.herokuapp.com/api/plan/x/democontract/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTFlY2FlMDAwZWM0NmJhNWYwOGQzNCIsImlhdCI6MTY0OTg3NTIzMiwiZXhwIjoxNjQ5OTYxNjMyfQ.NYNrFny3XvmYoCUEllRVC7YXj-ttegFBG6VyV0mMX3A

{
    "planID":"6241fac32e9d176352ea9419",
    "currency":"ETH"
}
###
GET http://127.0.0.1:8888/api/plan/x/democontract?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTFlY2FlMDAwZWM0NmJhNWYwOGQzNCIsImlhdCI6MTY0OTg3NTIzMiwiZXhwIjoxNjQ5OTYxNjMyfQ.NYNrFny3XvmYoCUEllRVC7YXj-ttegFBG6VyV0mMX3A

###
POST https://cominer.herokuapp.com/api/plan/x/contract/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDE2MjQ3MSwiZXhwIjoxNjUwMjQ4ODcxfQ.GHewjAKoUUH5xcs2HC8iWoPzYCxLK4Qkr9Z-Yw2q-bA

{
    "planID":"6259fef692fa2a9620d95438",
    "currency":"ETH"
}
###
GET http://127.0.0.1:8888/api/plan/x/contract?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDE2MjQ3MSwiZXhwIjoxNjUwMjQ4ODcxfQ.GHewjAKoUUH5xcs2HC8iWoPzYCxLK4Qkr9Z-Yw2q-bA

###
GET http://127.0.0.1:8888/api/plan/admin/getUserContracts/6251ecae000ec46ba5f08d34?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTgxMjk4MCwiZXhwIjoxNjQ5ODk5MzgwfQ.L4aEWo-zqvKDr1flfg0x_Tr4kXuqweeaa43oLTwtmws

###==================================ASIC============================================
POST http://127.0.0.1:8888/api/asic/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDQ5MDQ5MSwiZXhwIjoxNjUwNTc2ODkxfQ.gDnCiU9d3V9UVmuj3SMhOqfMcOglG4n0VlaueBUZW24

{
    "asicName":"AntMiner SX) 14T/s",
    "cryptoName":"BTC",
    "algorithm":"SHA-256",
    "hashPower":14000,
    "price":900,
    "hostFees":28
}
###
GET http://127.0.0.1:8888/api/asic?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI

###
GET http://127.0.0.1:8888/api/asic/admin?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI

###
GET http://127.0.0.1:8888/api/asic/621a62e000e949327e0dc11b?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTFlY2FlMDAwZWM0NmJhNWYwOGQzNCIsImlhdCI6MTY0OTgxODY5MiwiZXhwIjoxNjQ5OTA1MDkyfQ.9p3tFS-vGlWYIMXdr7M-fgPIrh6FN-Dh7KNASGnpSUU

###
PUT http://127.0.0.1:8888/api/asic/update/621a3e91b017345a26497416?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1IjoibWVubjk5ODc4NzZhYWRobTlkeHgiLCJpYXQiOjE2NDU4ODQyMzQsImV4cCI6MTY0NTk3MDYzNH0.y0cYbV0oJKQz6wFyO89Bjx7UzuzaM47A8lTOVu4RwiQ

{
    "asicName":"AntMiner E9",
    "cryptoName":"BTCx",
    "algorithm":"HASH-256",
    "hashPower":120000,
    "price":13000,
    "hostFees":200,
    "availability":true
}

###
DELETE  http://127.0.0.1:8888/api/asic/delete/621a3e91b017345a26497416?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1IjoibWVubjk5ODc4NzZhYWRobTlkeHgiLCJpYXQiOjE2NDU4ODQyMzQsImV4cCI6MTY0NTk3MDYzNH0.y0cYbV0oJKQz6wFyO89Bjx7UzuzaM47A8lTOVu4RwiQ

###==================================ASIC-CONTRACT============================================
POST http://127.0.0.1:8888/api/asic/x/contract/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDI1NTY3MiwiZXhwIjoxNjUwMzQyMDcyfQ.MV70RAdN-07BQ8qt65DBdDP-pdJ1xgpFxEHW5XqO-Go

{
    "asicID":"625cb040c1afd54a944d54da",
    "currency":"ETH"
}
###
GET http://127.0.0.1:8888/api/asic/x/contract?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDI1NTY3MiwiZXhwIjoxNjUwMzQyMDcyfQ.MV70RAdN-07BQ8qt65DBdDP-pdJ1xgpFxEHW5XqO-Go

###
GET http://127.0.0.1:8888/api/asic/x/contract/ondemand?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTgxMjk4MCwiZXhwIjoxNjQ5ODk5MzgwfQ.L4aEWo-zqvKDr1flfg0x_Tr4kXuqweeaa43oLTwtmws

###
PUT http://127.0.0.1:8888/api/asic/x/contract/activate/625ccd6b3f76858d5c96b4fa?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI

{
    "address":"mhbCuX9DngAvJynPJrJqAcz7jUz3vhnQPv",
    "workerID":"Rig_7862348"
}
###
PUT http://127.0.0.1:8888/api/asic/x/contract/expire/621aaa71edce9d7ecc1d4bca?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTFlY2FlMDAwZWM0NmJhNWYwOGQzNCIsImlhdCI6MTY0OTgxODY5MiwiZXhwIjoxNjQ5OTA1MDkyfQ.9p3tFS-vGlWYIMXdr7M-fgPIrh6FN-Dh7KNASGnpSUU

###
GET http://127.0.0.1:8888/api/asic/admin/getUserContracts/6251ecae000ec46ba5f08d34?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTgxMjk4MCwiZXhwIjoxNjQ5ODk5MzgwfQ.L4aEWo-zqvKDr1flfg0x_Tr4kXuqweeaa43oLTwtmws

###============================================ADMIN============================================
# POST http://127.0.0.1:8888/admin?key=XGYwZGFlXX0CI$6MTY76dhQXh@xNjQ4ODkzfQ2IDjGR0I6tps7zbinX
# Content-Type: application/json

# {
#     "email":"ahmed0103060120@gmail.com",
#     "password":"0103060120"
# }
###
POST http://127.0.0.1:8888/admin/FFAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "password":"0103060120"
}
###
POST http://127.0.0.1:8888/admin/2FAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "otp":"xEydK0bDUENYevbf"
}

###
POST http://127.0.0.1:8888/admin/getNewAccessToken?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTAyNTY5Mn0.VC-nKOkFezRVEeicD0SMZeQMBUChbJL5Q6N0-lEWi7o"
}
###
POST http://127.0.0.1:8888/admin/logout?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTAyNTY5Mn0.VC-nKOkFezRVEeicD0SMZeQMBUChbJL5Q6N0-lEWi7o"
}
###
GET http://127.0.0.1:8888/api/admin/getUsers?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTgxMjk4MCwiZXhwIjoxNjQ5ODk5MzgwfQ.L4aEWo-zqvKDr1flfg0x_Tr4kXuqweeaa43oLTwtmws

###
GET http://127.0.0.1:8888/admin/OVERVIEW?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json


###============================================TRANSACTIONS============================================
GET http://127.0.0.1:8888/api/transaction/getdepositaddress?currency=LTCT
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

###
GET http://127.0.0.1:8888/api/transaction/getdeposits
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

###
GET http://127.0.0.1:8888/api/transaction/getwithdraws
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

###
POST http://127.0.0.1:8888/api/transaction/setwithdrawrequest
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

{
    "currency":"LTCT",
    "amount":"0.9",
    "address":"moNpcwhxaCvfHWBsSBQ5QZme3GvMQMBsSv"
}
###
GET http://127.0.0.1:8888/api/transaction/admin/62577c039584aaa935963338/getUserdeposits
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTk3ODI3NywiZXhwIjoxNjUwMDY0Njc3fQ.Jd0BtfVOgfUAx30de4zXZRn35lQrTFRoTCepRUaAB9s

###
GET http://127.0.0.1:8888/api/transaction/admin/62577c039584aaa935963338/getUserwithdraws
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTk3ODI3NywiZXhwIjoxNjUwMDY0Njc3fQ.Jd0BtfVOgfUAx30de4zXZRn35lQrTFRoTCepRUaAB9s

###
GET http://127.0.0.1:8888/api/transaction/admin/getdepositaddressForAsicContarct?asicID=625ce35ab963f068f8bf6b08
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI
