# POST http://127.0.0.1:8888/api/user/sendVerificationMail?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
# Content-Type: application/json
# Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y2ZGNlNDZkZmRjMmU5ZmJkMDBlZCIsImlhdCI6MTY0ODM0MzcyMSwiZXhwIjoxNjQ4NDMwMTIxfQ.BX3q7PAsjal-JFJ61synBFOaqTm16rfrJpMZLozxvhE

# {
#     "email":"ab3atef@yahoo.com"
# }
###
GET http://127.0.0.1:8888/api/user/getUserData?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

###
POST http://127.0.0.1:8888/api/user/forgetPassword?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "email":"ahmed0103060120@gmail.com"
}

###
POST http://127.0.0.1:8888/api/user/verifyCode?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "email":"ahmed0103060120@gmail.com",
    "code":"9650425"
}
###
POST http://127.0.0.1:8888/api/user/resetPassword?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDYxOTE1MCwiZXhwIjoxNjUwNjE5MjEwfQ.X2EvLkY9SPqJE6Sj42qjrThrTHo8twS4vjkPyyRziPU

{
    "newPassword":"xxxxxxxx",
    "code":"9650425"
}
###
POST http://127.0.0.1:8888/api/user/register?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "userName":"vtrc&hyt",
    "email": "tERst@test.co",
    "phone": "98076258",
    "password": "sw@#$%^&*(ewc"
}

###
POST http://127.0.0.1:8888/api/user/FFactorAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "userName": "ayman",
    "password": "A@a123456"
}
###
POST http://127.0.0.1:8888/api/user/TwoFactorAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "userName": "ayman",
    "otp": "cMq1KBSWVabD71FG"
}
###
POST http://127.0.0.1:8888/api/user/logout?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTFlY2FlMDAwZWM0NmJhNWYwOGQzNCIsImlhdCI6MTY0OTgxMjg4MSwiZXhwIjoxNjQ5ODk5MjgxfQ.3yK8Ys7wzflqmbj42Sn6yMaL3rw7sENTWSHbv7oD9fM"
}

###
POST http://127.0.0.1:8888/api/user/getNewAccessToken?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "token":"--------------------------AyNDE2NX0.f9AowTkNEVNvicM0yx2B-QStcmAJIeA5bnlI97_lA_8"
}
###
GET http://127.0.0.1:8888/api/testAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y2ZGNlNDZkZmRjMmU5ZmJkMDBlZCIsImlhdCI6MTY0ODMyNjgwMiwiZXhwIjoxNjQ4NDEzMjAyfQ.4kvRFC24W5sTgfSWUxNN7yjjzcF14StVePtXfqZcL5A

###
PUT  http://127.0.0.1:8888/api/user/updatePassword?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y2ZGNlNDZkZmRjMmU5ZmJkMDBlZCIsImlhdCI6MTY0ODMyNjgwMiwiZXhwIjoxNjQ4NDEzMjAyfQ.4kvRFC24W5sTgfSWUxNN7yjjzcF14StVePtXfqZcL5A

{
    "password": "x",
    "newPassword": "xx"  
}

###
DELETE http://127.0.0.1:8888/api/user/deleteAccount?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzExZjVlOTM0MTczNjFlMjk1ZWRiZCIsImlhdCI6MTY0NzM4NjQ2NSwiZXhwIjoxNjQ3NDcyODY1fQ.iZVsV3YlvkISBlpPVQmzcr_v0HNTA7werLolRB6zkZQ

{
    "password": "x",
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzExZjVlOTM0MTczNjFlMjk1ZWRiZCIsImlhdCI6MTY0NzM4NjQ2NX0.yzBLy8LzawhpxNtFo_6JkVZ3ctBbAzBm_8Bcbrbiho0"
}

###==================================PLAN============================================
POST http://127.0.0.1:8888/api/plan/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDcwMTc3MiwiZXhwIjoxNjUwNzg4MTcyfQ.Cs64z98Cuu9ap3FmU2w4_Se8J_uqmGxYK91GbbcAe_A

{
    "planType":"lOnG",
    "planName":"GOLD LiteX",
    "cryptoName":"BtC",
    "algorithm":"SHA-256",
    "planDuration":2,
    "profitability":160,
    "price":9000
}
###
GET http://127.0.0.1:8888/api/plan?planType=loNg&cryptoName=BtC&key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDU5MTgwNCwiZXhwIjoxNjUwNjc4MjA0fQ.g4xeAfIClVIPkuxEuPqPJS4klNg-pK5C5ior0PpE6lU

###
GET http://127.0.0.1:8888/api/plan/admin?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI

###
GET http://127.0.0.1:8888/api/plan/620a3e3e50d15271dd99d31a?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1IjoibWVubjk5ODc4NzZhYWRobTlkeHgiLCJpYXQiOjE2NDU4ODQyMzQsImV4cCI6MTY0NTk3MDYzNH0.y0cYbV0oJKQz6wFyO89Bjx7UzuzaM47A8lTOVu4RwiQ

###
PUT http://127.0.0.1:8888/api/plan/update/62622322fabaa330a520d66e?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

{
    "planType":"long",
    "planName":"regular",
    "cryptoName":"btc",
    "algorithm":"ethash",
    "planDuration":1,
    "profitability":150,
    "price":1000,
    "availability":"true"
}

###
DELETE  http://127.0.0.1:8888/api/plan/delete/62151626448be90dcf016713?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###==================================PLAN-CONTRACT============================================
POST https://cominer.herokuapp.com/api/plan/x/democontract/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTFlY2FlMDAwZWM0NmJhNWYwOGQzNCIsImlhdCI6MTY0OTg3NTIzMiwiZXhwIjoxNjQ5OTYxNjMyfQ.NYNrFny3XvmYoCUEllRVC7YXj-ttegFBG6VyV0mMX3A

{
    "planID":"6241fac32e9d176352ea9419",
    "currency":"ETH"
}
###
GET http://127.0.0.1:8888/api/plan/x/democontract?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTFlY2FlMDAwZWM0NmJhNWYwOGQzNCIsImlhdCI6MTY0OTg3NTIzMiwiZXhwIjoxNjQ5OTYxNjMyfQ.NYNrFny3XvmYoCUEllRVC7YXj-ttegFBG6VyV0mMX3A

###
POST https://cominer.herokuapp.com/api/plan/x/contract/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDE2MjQ3MSwiZXhwIjoxNjUwMjQ4ODcxfQ.GHewjAKoUUH5xcs2HC8iWoPzYCxLK4Qkr9Z-Yw2q-bA

{
    "planID":"6259fef692fa2a9620d95438",
    "currency":"ETH"
}
###
GET http://127.0.0.1:8888/api/plan/x/contract?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDE2MjQ3MSwiZXhwIjoxNjUwMjQ4ODcxfQ.GHewjAKoUUH5xcs2HC8iWoPzYCxLK4Qkr9Z-Yw2q-bA

###
GET http://127.0.0.1:8888/api/plan/admin/getUserContracts/6251ecae000ec46ba5f08d34?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTgxMjk4MCwiZXhwIjoxNjQ5ODk5MzgwfQ.L4aEWo-zqvKDr1flfg0x_Tr4kXuqweeaa43oLTwtmws

###==================================ASIC============================================
POST http://127.0.0.1:8888/api/asic/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

{
    "asicName":"AntMiner SX) 14T/s",
    "cryptoName":"BTC",
    "algorithm":"SHA-256",
    "hashPower":14000,
    "price":900,
    "hostFees":28
}
###
GET http://127.0.0.1:8888/api/asic?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI

###
GET http://127.0.0.1:8888/api/asic/admin?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI

###
GET http://127.0.0.1:8888/api/asic/621a62e000e949327e0dc11b?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###
PUT http://127.0.0.1:8888/api/asic/update/621a3e91b017345a26497416?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

{
    "asicName":"AntMiner E9",
    "cryptoName":"BTC",
    "algorithm":"sha-256",
    "hashPower":120000,
    "price":13000,
    "hostFees":20,
    "availability":true
}

###
DELETE  http://127.0.0.1:8888/api/asic/delete/621a3e91b017345a26497416?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###==================================ASIC-CONTRACT============================================
POST http://127.0.0.1:8888/api/asic/x/contract/add?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MjkyNTAxNSwiZXhwIjoxNjUzMDExNDE1fQ.fL-7M_Q_ojHC8om-43Kaw2V8JQu5JBj6H0E4l3nUpYI

{
    "asicID":"6263b65d780e74664cd5f26e",
    "currency":"eth"
}
###
GET http://127.0.0.1:8888/api/asic/x/contract?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDI1NTY3MiwiZXhwIjoxNjUwMzQyMDcyfQ.MV70RAdN-07BQ8qt65DBdDP-pdJ1xgpFxEHW5XqO-Go

###
GET http://127.0.0.1:8888/api/asic/x/contract/ondemand?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDU5MDYyMCwiZXhwIjoxNjUwNjc3MDIwfQ.ih81ssDZ3iDHnyfR6IvDSXN6JZ-hIroiX97j1bfMl9I

###
PUT http://127.0.0.1:8888/api/asic/x/contract/activate/626279fe9f0dfdffc879c339?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

{
    "address":"mhbCuX9DngAvJynPJrJqAcz7jUz3vhnQPv",
    "workerID":"Rig_7862348",
    "pool":"test"
}
###
PUT http://127.0.0.1:8888/api/asic/x/contract/expire/621aaa71edce9d7ecc1d4bca?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###
GET http://127.0.0.1:8888/api/asic/admin/getUserContracts/6251ecae0jhh00ec46ba5f08d34?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###============================================ADMIN============================================
# POST http://127.0.0.1:8888/admin?key=XGYwZGFlXX0CI$6MTY76dhQXh@xNjQ4ODkzfQ2IDjGR0I6tps7zbinX
# Content-Type: application/json

# {
#     "email":"ahmed0103060120@gmail.com",
#     "password":"0103060120"
# }
###
POST http://127.0.0.1:8888/admin/FFAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "password":"0103060120"
}
###
POST http://127.0.0.1:8888/admin/2FAuth?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "otp":"xEydK0bDUENYevbf"
}

###
POST http://127.0.0.1:8888/admin/getNewAccessToken?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTAyNTY5Mn0.VC-nKOkFezRVEeicD0SMZeQMBUChbJL5Q6N0-lEWi7o"
}
###
POST http://127.0.0.1:8888/admin/logout?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTAyNTY5Mn0.VC-nKOkFezRVEeicD0SMZeQMBUChbJL5Q6N0-lEWi7o"
}
###
GET http://127.0.0.1:8888/api/admin/getUsers?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDU5MDYyMCwiZXhwIjoxNjUwNjc3MDIwfQ.ih81ssDZ3iDHnyfR6IvDSXN6JZ-hIroiX97j1bfMl9I

###
GET http://127.0.0.1:8888/admin/OVERVIEW?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MjA5MTUzMCwiZXhwIjoxNjUyMTc3OTMwfQ.VAaVsaSR1qdi7t0XdsLDk_hY_HHWtzsk8MlvYycSBCE

###============================================TRANSACTIONS============================================
GET http://127.0.0.1:8888/api/transaction/getdepositaddress?currency=LTCT
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

###
GET http://127.0.0.1:8888/api/transaction/getdeposits
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

###
GET http://127.0.0.1:8888/api/transaction/getwithdraws
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

###
POST http://127.0.0.1:8888/api/transaction/setwithdrawrequest
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MDA3NTE2NywiZXhwIjoxNjUwMTYxNTY3fQ.GYOvqM7waXLPYf8q4FE4fUYNCLKXwFIK2_kih4_Bq8E

{
    "currency":"LTCT",
    "amount":"0.9",
    "address":"moNpcwhxaCvfHWBsSBQ5QZme3GvMQMBsSv"
}
###
GET http://127.0.0.1:8888/api/transaction/admin/62577c039584aaa935963338/getUserdeposits
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTk3ODI3NywiZXhwIjoxNjUwMDY0Njc3fQ.Jd0BtfVOgfUAx30de4zXZRn35lQrTFRoTCepRUaAB9s

###
GET http://127.0.0.1:8888/api/transaction/admin/62577c039584aaa935963338/getUserwithdraws
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY0OTk3ODI3NywiZXhwIjoxNjUwMDY0Njc3fQ.Jd0BtfVOgfUAx30de4zXZRn35lQrTFRoTCepRUaAB9s

###
GET http://127.0.0.1:8888/api/transaction/admin/getdepositaddressForAsicContarct?asicID=625ce35ab963f068f8bf6b08
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDI0MTI3MCwiZXhwIjoxNjUwMzI3NjcwfQ.uYWjMMI5JFXL7vL7BHb9MEExazuWlJ81_0loeyhU9cI

###============================================FARM============================================

POST http://127.0.0.1:8888/api/farm/addworker?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

{
    "workerName":"AntMiners9",
    "address":"waeudytwvqut&mhbCuX9DngAvJynPJrJqAcz7jUz3vhnQPv",
    "workerID":"test",
    "pool":"test"
}
###
delete http://127.0.0.1:8888/api/farm/deleteworker/6263563899c501b26e2539a5?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###
PUT http://127.0.0.1:8888/api/farm/endworker/62635a2e372f281e6e35f8d0?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###
GET http://127.0.0.1:8888/api/farm/getactiveworkers?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###
GET http://127.0.0.1:8888/api/farm/getnotactiveworkers?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MDY2NzY3NywiZXhwIjoxNjUwNzU0MDc3fQ.6LqQupj6lUosVq5qCSpM8M8IkUxtLjDPsKrdkmpTkmE

###============================================SELLER============================================
POST http://127.0.0.1:8888/api/seller/createsellerstore?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MTA5NTYwMCwiZXhwIjoxNjUxMTgyMDAwfQ.tw0jovaBNL1K-yXcAF52t5oFfDTz7qnTJQepE33laJs

###
GET http://127.0.0.1:8888/api/seller/getworkers?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MTIzNzUyNCwiZXhwIjoxNjUxMzIzOTI0fQ.6bb-zU2Fc563rtf19LcFlRLc5QphV8PcVDtW2ZkawCg

###
POST http://127.0.0.1:8888/api/seller/addworkerplan/6268e57a4ae12d67bb9bd019?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MTA5NTYwMCwiZXhwIjoxNjUxMTgyMDAwfQ.tw0jovaBNL1K-yXcAF52t5oFfDTz7qnTJQepE33laJs

{
    "planName":"testPlan2",
    "price":400,
    "hashPower":12000
}
###
PUT http://127.0.0.1:8888/api/seller/updateworkerplan/6268e57a4ae12d67bb9bd019/626a0442f6d89862062afce8?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MTA5NTYwMCwiZXhwIjoxNjUxMTgyMDAwfQ.tw0jovaBNL1K-yXcAF52t5oFfDTz7qnTJQepE33laJs

{
    "planName":"testPlan 45",
    "price":90,
    "hashPower":300
}
###
DELETE http://127.0.0.1:8888/api/seller/deleteworkerplan/6268e57a4ae12d67bb9bd019/626a0176f25f3600fab9b5f6?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTc3YzAzOTU4NGFhYTkzNTk2MzMzOCIsImlhdCI6MTY1MTA5NTYwMCwiZXhwIjoxNjUxMTgyMDAwfQ.tw0jovaBNL1K-yXcAF52t5oFfDTz7qnTJQepE33laJs

###
GET http://127.0.0.1:8888/api/seller/getworkerplans/6268e57a4ae12d67bb9bd019?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk0YzFjNjUxMjI5ODkwNGQ3MjZlNSIsImlhdCI6MTY1MTIzMzg2OSwiZXhwIjoxNjUxMzIwMjY5fQ.2Hkw09CLklcp-BZk9uAmO4pqtsycspQwXF9B6WCXUwQ

###
GET http://127.0.0.1:8888/api/seller/getsellers?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk0YzFjNjUxMjI5ODkwNGQ3MjZlNSIsImlhdCI6MTY1MTIzMzg2OSwiZXhwIjoxNjUxMzIwMjY5fQ.2Hkw09CLklcp-BZk9uAmO4pqtsycspQwXF9B6WCXUwQ

###
GET http://127.0.0.1:8888/api/seller/getsellerplans/62577c039584aaa935963338?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk0YzFjNjUxMjI5ODkwNGQ3MjZlNSIsImlhdCI6MTY1MTIzMzg2OSwiZXhwIjoxNjUxMzIwMjY5fQ.2Hkw09CLklcp-BZk9uAmO4pqtsycspQwXF9B6WCXUwQ

###
POST http://127.0.0.1:8888/api/seller/addplancontarct?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk0YzFjNjUxMjI5ODkwNGQ3MjZlNSIsImlhdCI6MTY1MTIzMzg2OSwiZXhwIjoxNjUxMzIwMjY5fQ.2Hkw09CLklcp-BZk9uAmO4pqtsycspQwXF9B6WCXUwQ

{
    "planID":"626a218a28ea42451385cdb3",
    "currency":"eth"
}

###
GET http://127.0.0.1:8888/api/seller/getplancontracts/6268e57a4ae12d67bb9bd019?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk0YzFjNjUxMjI5ODkwNGQ3MjZlNSIsImlhdCI6MTY1MTIzMzg2OSwiZXhwIjoxNjUxMzIwMjY5fQ.2Hkw09CLklcp-BZk9uAmO4pqtsycspQwXF9B6WCXUwQ

###======================================ADMIN=================
GET http://127.0.0.1:8888/api/seller/admin/getsellers?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MTIyNTU4MywiZXhwIjoxNjUxMzExOTgzfQ.ks7d_QOqhxLYmOQXo1KXr3lBcrH96QDln5Oe-gjErWA

###
GET http://127.0.0.1:8888/api/seller/admin/getworkers/62577c039584aaa935963338?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MjkyNDI5OCwiZXhwIjoxNjUzMDEwNjk4fQ.KFgILFYgg3Haeyi05l6RZ7Rq3a5W-SwMfMHGWh1V_7o

###
GET http://127.0.0.1:8888/api/seller/admin/getworkerplans/6268e57a4ae12d67bb9bd019?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MTIyNTU4MywiZXhwIjoxNjUxMzExOTgzfQ.ks7d_QOqhxLYmOQXo1KXr3lBcrH96QDln5Oe-gjErWA

###
GET http://127.0.0.1:8888/api/seller/admin/getplancontracts/6268e57a4ae12d67bb9bd019?key=c3fe929c35dd0cbcc8f062bb60e9d2ce7d14be21513d07c53e370d81ba9de4a4
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDlmNzA5NGY4ODVmNDg5YjdhYzhkNiIsImlhdCI6MTY1MTIyNTU4MywiZXhwIjoxNjUxMzExOTgzfQ.ks7d_QOqhxLYmOQXo1KXr3lBcrH96QDln5Oe-gjErWA
